
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wzvghlwuwwkqnrfuvfgm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6dmdobHd1d3drcW5yZnV2ZmdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3NzA5NTYsImV4cCI6MjA2MDM0Njk1Nn0.t4R3yOIeyA9J6HwqFu56r7cEzxk2bIkd6AbNxYi6JVk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);
